#!/bin/bash

PATH_I=/scran/input/ #change path here
PATH_O=/scran/output/ #change path here
PATH_T=/scran/scripts/ #change path here

m_file=counts_v1.mtx
g_file=genes.csv
bc_file=cells.csv
ofile=sct_counts_v1.csv
tfile=run_scran.R

Rscript $PATH_T$tfile $PATH_I$m_file $PATH_I$g_file $PATH_I$bc_file $PATH_O$ofile

